# -*- coding: utf-8 -*-
import sys
import time

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gameWindow(object):
    def __init__(self, Client):
        self.client = Client
        self.game_starting = None
        self.opened = False

    def setupUi(self, gameWindow):
        print("entered setup")
        gameWindow.setObjectName("gameWindow")
        gameWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(gameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.game_table = QtWidgets.QTableWidget(self.centralwidget)
        self.game_table.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.game_table.setStyleSheet(";background-color:rgb(255, 255, 255);\n"
                                      "border:1px solid red\n"
                                      ";gridline-color: rgb(170, 85, 255);\n"
                                      "text-color:rgb(255, 85, 127)")
        self.game_table.setAlternatingRowColors(True)
        self.game_table.setObjectName("game_table")
        self.game_table.setColumnCount(7)
        self.game_table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(6, item)
        for i in range(3):
            for j in range(7):
                item = QtWidgets.QTableWidgetItem()
                self.game_table.setItem(i, j, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setItem(1, 1, item)
        self.game_table.horizontalHeader().setStretchLastSection(False)
        self.game_table.verticalHeader().setCascadingSectionResizes(False)
        self.game_table.verticalHeader().setStretchLastSection(False)
        self.game_starting = QtWidgets.QLabel(self.centralwidget)
        self.game_starting.setGeometry(QtCore.QRect(90, 390, 331, 51))
        self.game_starting.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.game_starting.setObjectName("game_starting")
        self.game_starting.hide()
        self.waiting_players = QtWidgets.QLabel(self.centralwidget)
        self.waiting_players.setGeometry(QtCore.QRect(80, 430, 371, 51))
        self.waiting_players.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.waiting_players.setObjectName("waiting_players")
        self.continue_button = QtWidgets.QPushButton(self.centralwidget)
        self.continue_button.setGeometry(QtCore.QRect(260, 290, 311, 91))
        self.continue_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                           "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.continue_button.setObjectName("continue_button")
        self.continue_button.hide()
        self.three = QtWidgets.QLabel(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(510, 440, 31, 41))
        self.three.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.three.setObjectName("three")
        self.three.hide()
        self.two = QtWidgets.QLabel(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(480, 440, 31, 41))
        self.two.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.two.setObjectName("two")
        self.two.hide()
        self.enter_word = QtWidgets.QLabel(self.centralwidget)
        self.enter_word.setGeometry(QtCore.QRect(280, 280, 251, 31))
        self.enter_word.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.enter_word.setObjectName("two")
        self.enter_word.hide()
        self.word_text = QtWidgets.QLineEdit(self.centralwidget)
        self.word_text.setGeometry(QtCore.QRect(280, 320, 251, 51))
        self.word_text.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.word_text.setObjectName("word_text")
        self.word_text.hide()
        self.one = QtWidgets.QLabel(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(450, 440, 31, 41))
        self.one.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.one.setObjectName("one")
        self.one.hide()
        self.round_time = QtWidgets.QLabel(self.centralwidget)
        self.round_time.setGeometry(QtCore.QRect(160, 470, 461, 81))
        self.round_time.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.round_time.setObjectName("round_time")
        self.round_time.hide()
        self.submit_word = QtWidgets.QPushButton(self.centralwidget)
        self.submit_word.setGeometry(QtCore.QRect(540, 320, 191, 51))
        self.submit_word.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.submit_word.setObjectName("submit_word")
        self.submit_word.hide()
        gameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        gameWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gameWindow)
        self.statusbar.setObjectName("statusbar")
        gameWindow.setStatusBar(self.statusbar)

        self.retranslateUi(gameWindow)
        QtCore.QMetaObject.connectSlotsByName(gameWindow)

        self.check_for_button(gameWindow)

    def retranslateUi(self, gameWindow):
        _translate = QtCore.QCoreApplication.translate
        gameWindow.setWindowTitle(_translate("gameWindow", "MainWindow"))
        item = self.game_table.verticalHeaderItem(0)
        item.setText(_translate("gameWindow", "letter1"))
        item = self.game_table.verticalHeaderItem(1)
        item.setText(_translate("gameWindow", "letter2"))
        item = self.game_table.verticalHeaderItem(2)
        item.setText(_translate("gameWindow", "letter3"))
        item = self.game_table.horizontalHeaderItem(0)
        item.setText(_translate("gameWindow", "country"))
        item = self.game_table.horizontalHeaderItem(1)
        item.setText(_translate("gameWindow", "capital"))
        item = self.game_table.horizontalHeaderItem(2)
        item.setText(_translate("gameWindow", "boy name"))
        item = self.game_table.horizontalHeaderItem(3)
        item.setText(_translate("gameWindow", "movie"))
        item = self.game_table.horizontalHeaderItem(4)
        item.setText(_translate("gameWindow", "animal"))
        item = self.game_table.horizontalHeaderItem(5)
        item.setText(_translate("gameWindow", "fruit and veggies"))
        item = self.game_table.horizontalHeaderItem(6)
        item.setText(_translate("gameWindow", "household-item"))
        __sortingEnabled = self.game_table.isSortingEnabled()
        self.game_table.setSortingEnabled(False)
        self.game_table.setSortingEnabled(__sortingEnabled)
        self.game_starting.setText(_translate("gameWindow", "Round starting in "))
        self.three.setText(_translate("gameWindow", "."))
        self.two.setText(_translate("gameWindow", "."))
        self.one.setText(_translate("gameWindow", "."))
        self.round_time.setText(_translate("gameWindow", "round timer 30 seconds"))
        self.continue_button.setText(_translate("gameWindow", "continue"))
        self.waiting_players.setText(_translate("gameWindow", "waiting for players"))
        self.enter_word.setText(_translate("gameWindow", "enter word"))
        self.submit_word.setText(_translate("gameWindow", "submit"))

    def check_for_button(self, MainWindow):
        self.continue_button.clicked.connect(lambda: self.continue_pressed(MainWindow))
        self.submit_word.clicked.connect(lambda: self.send_word(MainWindow))

    def send_word(self, MainWindow):
        print("sendpressed")
        self.client.curr_word = self.word_text.text()

    def continue_pressed(self, MainWindow):
        print("continuepressed")
        self.client.screen_state = 2
        MainWindow.close()

    def insert_value(self, category, round_num, word):
        _translate = QtCore.QCoreApplication.translate
        item = self.game_table.item(round_num - 1, category)
        item.setText(_translate("gameWindow", word))

    def start_round(self):
        if self.client.voice is False:
            self.enter_word.show()
            self.submit_word.show()
            self.word_text.show()
        self.game_starting.show()
        time.sleep(1)
        self.one.show()
        time.sleep(1)
        self.two.show()
        time.sleep(1)
        self.three.show()
        time.sleep(1)
        self.game_starting.hide()
        self.one.hide()
        self.two.hide()
        self.three.hide()

    def set_letter(self, round_num, letter):
        _translate = QtCore.QCoreApplication.translate
        item = self.game_table.verticalHeaderItem(round_num - 1)
        item.setText(_translate("gameWindow", letter))

    def waiting_for_players(self):
        while self.client.game_start is False:
            self.one.show()
            time.sleep(1)
            if self.client.game_start is True:
                break
            self.two.show()
            time.sleep(1)
            if self.client.game_start is True:
                break
            self.three.show()
            time.sleep(1)
            if self.client.game_start is True:
                break
            self.one.hide()
            self.two.hide()
            self.three.hide()
            time.sleep(1)
        self.round_time.show()
        self.one.hide()
        self.two.hide()
        self.three.hide()
        self.waiting_players.hide()


def show_game(window):
    app2 = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    window.opened = True
    sys.exit(app2.exec_())
